FROM jenkins/jenkins:lts-jdk17

ENV JENKINS_USER=admin
ENV JENKINS_PASS=123456
ENV JAVA_OPTS=-Djenkins.install.runSetupWizard=false


USER root
RUN apt-get update -y && \
    apt-get install -y python3 python3-pip docker.io


ADD plugins.txt .
RUN jenkins-plugin-cli -f plugins.txt
ADD ssh-config .


ADD start.sh .
RUN mkdir /deploy
RUN chown jenkins:jenkins /deploy


RUN apt-get install -y maven

ENTRYPOINT [ "/start.sh" ]
